// Can appear on the board, on a card, or in a colony.
export enum Resource {
    ANIMAL = 'resourceAnimal',
    CAMP = 'resourceCamp',
    CARD = 'resourceCard',
    ENERGY = 'resourceEnergy',
    FIGHTER = 'resourceFighter',
    FLOATER = 'resourceFloater',
    HEAT = 'resourceHeat',
    MEGACREDIT = 'resourceMegacredit',
    MICROBE = 'resourceMicrobe',
    PLANT = 'resourcePlant',
    SCIENCE = 'resourceScience',
    STEEL = 'resourceSteel',
    TITANIUM = 'resourceTitanium',
    ASTEROID = 'asteroid',
    ANY_STORABLE_RESOURCE = 'anyStorableResource',
    ANY_STANDARD_RESOURCE = 'anyStandardResource',
    PRESERVATION = 'resourcePreservation',
}
