import {Amount} from './action';

export enum VariableAmount {
    USER_CHOICE = 'userChoice',
    BASED_ON_USER_CHOICE = 'basedOnUserChoice',
    CITIES_ON_MARS = 'citiesOnMars',
    CITY_TILES_IN_PLAY = 'cityTilesInPlay',
    JOVIAN_TAGS = 'jovianTags',
    EARTH_TAGS = 'earthTags',
    RESOURCES_ON_CARD = 'resourcesOnCard',
    TWICE_RESOURCES_ON_CARD = 'twiceResourcesOnCard',
    OPPONENTS_SPACE_TAGS = 'opponentsSpaceTags',
    POWER_TAGS = 'powerTags',
    ALL_EVENTS = 'allEvents',
    PLANT_TAGS = 'plantTags',
    SPACE_TAGS = 'spaceTags',
    VENUS_AND_EARTH_TAGS = 'venusAndEarthTags',
    VENUS_TAGS = 'venusTags',
    COLONIES = 'colonies',
    ALL_COLONIES = 'allColonies',
    OCEANS_ADJACENT_TO_CAPITAL = 'oceansAdjacentToCapital',
    HALF_RESOURCES_ON_CARD = 'halfResourcesOnCard',
    QUARTER_RESOURCES_ON_CARD = 'quarterResourcesOnCard',
    CITY_TILES_ADJACENT_TO_COMMERCIAL_DISTRICT = 'cityTilesAdjacentToCommercialDistrict',
    THIRD_RESOURCES_ON_CARD = 'thirdResourcesOnCard',
    HALF_MICROBE_TAGS = 'halfMicrobeTags',
    CARDS_WITHOUT_TAGS = 'cardsWithoutTags',
    HALF_ALL_COLONIES = 'halfAllColonies',
    MINING_AREA_CELL_HAS_STEEL_BONUS = 'miningAreaCellHasSteelBonus',
    MINING_AREA_CELL_HAS_TITANIUM_BONUS = 'miningAreaCellHasTitaniumBonua',
    MINING_RIGHTS_CELL_HAS_STEEL_BONUS = 'miningRightsCellHasSteelBonus',
    MINING_RIGHTS_CELL_HAS_TITANIUM_BONUS = 'miningRightsCellHasTitaniumBonus',
    TRIPLE_BASED_ON_USER_CHOICE = 'tripleBasedOnUserChoice',
    HALF_BUILDING_TAGS = 'halfBuildingTags',
    THREE_IF_SEARCH_FOR_LIFE_HAS_ONE_OR_MORE_RESOURCES = 'threeIfSearchForLifeHasOneOrMoreResources',
    FOUR_IF_THREE_PLANT_TAGS_ELSE_ONE = 'fourIfThreePlantTagsElseOne',
    THIRD_ALL_CITIES = 'thirdAllCities',
    REVEALED_CARD_MICROBE = 'revealedCardMicrobe',
}
