export enum ApiActionType {
    API_PLAY_CARD = 'apiPlayCard',
    API_PLAY_CARD_ACTION = 'apiPlayCardAction',
    API_PLAY_STANDARD_PROJECT = 'apiPlayStandardProject',
    API_CLAIM_MILESTONE = 'apiClaimMilestone',
    API_FUND_AWARD = 'apiFundAward',
    API_DO_CONVERSION = 'apiDoConversion',
    API_SKIP_ACTION = 'apiSkipAction',
    API_PASS_GENERATION = 'apiPassGeneration',
    API_COMPLETE_PLACE_TILE = 'apiCompletePlaceTile',
    API_COMPLETE_CHOOSE_RESOURCE_ACTION_DETAILS = 'apiCompleteChooseResourceActionDetails',
    API_SKIP_CHOOSE_RESOURCE_ACTION_DETAILS = 'apiSkipChooseResourceActionDetails',
    API_CONFIRM_CARD_SELECTION = 'apiConfirmCardSelection',
    API_CONTINUE_AFTER_REVEALING_CARDS = 'apiContinueAfterRevealingCards',
    API_COMPLETE_CHOOSE_DUPLICATE_PRODUCTION = 'apiCompleteChooseDuplicateProduction',
    API_SKIP_CHOOSE_DUPLICATE_PRODUCTION = 'apiSkipChooseDuplicateProduction',
    API_INCREASE_LOWEST_PRODUCTION = 'apiIncreaseLowestProduction',
    API_TRADE = 'apiTrade',
    API_TRADE_FOR_FREE = 'apiTradeForFree',
    API_COMPLETE_BUILD_COLONY = 'apiCompletePlaceColony',
    API_COMPLETE_INCREASE_AND_DECREASE_COLONY_TILE_TRACKS = 'apiCompleteIncreaseAndDecreaseColonyTileTracks',
    API_COMPLETE_PUT_ADDITIONAL_COLONY_TILE_INTO_PLAY = 'apiCompletePutAdditionalColonyTileIntoPlay',
    API_COMPLETE_CHOOSE_NEXT_ACTION = 'apiCompleteChooseNextAction',
    API_START_OVER = 'apiStartOver',
}
