export enum ApiActionType {
    API_PLAY_CARD = 'apiPlayCard',
    API_PLAY_CARD_ACTION = 'apiPlayCardAction',
    API_PLAY_STANDARD_PROJECT = 'apiPlayStandardProject',
    API_CLAIM_MILESTONE = 'apiClaimMilestone',
    API_FUND_AWARD = 'apiFundAward',
    API_DO_CONVERSION = 'apiDoConversion',
    API_SKIP_ACTION = 'apiSkipAction',
    API_COMPLETE_PLACE_TILE = 'apiCompletePlaceTile',
    API_COMPLETE_CHOOSE_RESOURCE_ACTION_DETAILS = 'apiCompleteChooseResourceActionDetails',
    API_SKIP_CHOOSE_RESOURCE_ACTION_DETAILS = 'apiSkipChooseResourceActionDetails',
    API_CONFIRM_CARD_SELECTION = 'apiConfirmCardSelection',
    API_CONTINUE_AFTER_REVEALING_CARDS = 'apiContinueAfterRevealingCards',
    API_COMPLETE_CHOOSE_DUPLICATE_PRODUCTION = 'apiCompleteChooseDuplicateProduction',
    API_SKIP_CHOOSE_DUPLICATE_PRODUCTION = 'apiSkipChooseDuplicateProduction',
    API_INCREASE_LOWEST_PRODUCTION = 'apiIncreaseLowestProduction',
    API_TRADE = 'apiTrade',
    API_COMPLETE_BUILD_COLONY = 'apiCompleteBuildColony',
}
